name: Update game manifests

on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-scripts-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Populate generated dir
        run: |
          mkdir -p scripts/generated
          jq -r .manifests[] repository.json | while read -r manifest; do
            echo "Copying manifest: $manifest"
            cp $manifest scripts/generated/
          done

      - name: Run all scripts
        run: |
          for script in scripts/*.py; do
            echo "======================================"
            echo "Running script: $script"
            echo "--------------------------------------"
            uv run $script
            status=$?
            if [ $status -eq 0 ]; then
              echo "Script $script completed successfully."
            else
              echo "Script $script failed with exit code $status."
            fi
            echo "======================================"
            echo
          done

      - name: Move generated JSONs to root
        run: mv scripts/generated/*.json .

      - name: Direct push safe manifests
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.json
          if git diff --cached --quiet; then
            echo "" >> $GITHUB_OUTPUT
          else
            git commit -m "Automated: Update safe manifests"
            git push origin main
            git fetch origin main
          fi
