name: Update manifests

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Copy to generated
        run: |
          mkdir -p scripts/generated
          jq -r .manifests[] repository.json | while read -r manifest; do
            echo "Copying manifest: $manifest"
            cp $manifest scripts/generated/
          done

      - name: Run scripts
        run: |
          for script in scripts/*.py; do
            echo "======================================"
            echo "Running script: $script"
            echo "--------------------------------------"
            uv run $script
            status=$?
            if [ $status -eq 0 ]; then
              echo "Script $script completed successfully."
            else
              echo "Script $script failed with exit code $status."
            fi
            echo "======================================"
            echo
          done

      - name: Move from generated
        run: mv scripts/generated/*.json .

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.json

          if ! git diff --cached --quiet; then
            git commit -m "chore(manifests): :robot: update"
            git push origin main
          fi
